### ISSUE TITLE
Rounded bpm in Guess function. 

### ISSUE THREAD

**Issue by robert8888** [chrisguttandin/web-audio-beat-detector#343]
What sens have rounding bpm value in  guess function ?? I need offset and bpm value. To have accurate bpm value I need to run analyze function, and to have offset value I need to run guess function.... Both analyze and guess function use this same algorithm so this runs computeTempoBuckets twice.

If someone need  an offset value, I think that is there bigger chance that he needs more accurate information about beat. . 

In my opinion this Math.round(bpm) is'nt any favor for library user. Anybody can / should transform output  to expected format  floor, ceil, fixed no matter what is needed. Current approach limits this possibility. 

What's more. Guess function use this rounded value of bpm only to determine is that offset in range of first beat  (is less that beat length). I think that will work even more accurate without rounding bpm (I guess, don't tested it)

Will it be possible (taking into account backward compatibility) to change this behavior ? Or should I clone project and tune it to my needs ?

**Comment by mindsocket** [comment]
I ran into this issue also. From a couple of tests it seems reasonable to round to 2-3 decimal places, but rounding to whole numbers does cause issues for some music.

**Comment by chrisguttandin** [comment]
Hi @robert8888, sorry for the delay.

The reason for rounding the value to full bpm is that the algorithm isn't very accurate and it more or less only works for music with a strong baseline. Since that music is mostly computer generated and it oftentimes uses full bpm values the value is rounded. These are a lot of assumptions and as with any other generalization there will be exceptions where this doesn't work. The bpm value is a guess, hence the function's name.

The offset returned by `guess()` is not rounded but it's also not very accurate. It's just the offset of the very first peak of the `tempoBucket` with the highest score. That offset is then used to guess the offset of the very first beat in the `AudioBuffer`. 

Is that what you actually want? I'm asking because I don't really know how to add that functionality in a backwards compatible way. My hope is that we find a way by better defining the use case.

**Comment by mindsocket** [comment]
Thanks for considering this! I've been using a desktop tool (Mixxx) for BPM detection and have manually verified songs (using Reaper) for tempo accuracy and constancy. In the examples listed below very few needed manual adjustment and came straight from Mixxx. It seems there are indeed some songs, for some unknown reason, with a reliably constant but non-integer tempo.  For that reason, I think it's worth considering rounding to 2-3 decimal places and using that for the offset guess, as well as the returned tempo.

![image](https://user-images.githubusercontent.com/289376/104151917-48b74380-5432-11eb-850f-65f0cc60be34.png)

Alternative 1: Round only if the guess is really close to a whole number

Alternative 2: A separate function that returns the raw tempoBucket and offset data. This would give the caller latitude to make their own decisions, like ascertaining whether the data is reliable (perhaps many buckets means no constancy?), or handling songs with mixed tempos (eg a slow bridge).

For broader context, below is a view of my use case - it's a browser based interface to help work out tempo and cue point for a song, augmented by guesses from this library, and a visual plot that gives clues as to accuracy of analysis. This makes it easy to see when there's tempo drift in the audio. That is unfortunately the case in this example where the beats for each measure aren't vertically aligned, meaning there's not much point guessing the tempo.

![image](https://user-images.githubusercontent.com/289376/104152471-c6c81a00-5433-11eb-868a-24798689214b.png)

**Comment by chrisguttandin** [comment]
That's an excellent tool. I would love to play around with it. Is that tool available on the internet?

If there is one thing I know for sure about beat detection algorithms it is that they will never be perfect. No matter what you do to optimize them it will introduce a flaw for some edge cases which you haven't considered. That's why the goal for building this library - by implementing Joe's idea - was to build something lightweight which would work surprisingly well. Knowing that it will for sure not be as elaborate as it could be.

That's why I think a tool like yours could be extremely valuable to show the different algorithms side by side.

As far as I know the beat detection algorithm that comes with Mixxx is based on the one published by the Queen Mary University. It's the work of Matthew Davies and others. It's much more sophisticated (and resource hungry) than the algorithm used here. In case you're interested there is also a [collection of VAMP plugins published by Queen Mary](https://vamp-plugins.org/plugin-doc/qm-vamp-plugins.html) with similar algorithms.

Another library which offers advanced algorithms is Essentia: https://essentia.upf.edu/algorithms_reference.html. It comes with an [official JS version](https://mtg.github.io/essentia.js) that can be used in the browser. It is of course a larger bundle and it takes longer to process but it would be very nice to see the result you get from Essentia next to the one from web-audio-beat-detector. Essentia will also give you every single beat it detected.

**Comment by robert8888** [comment]
In my case I need accurate bpm and offset info to make beatmaching. I provide 3 ways - fetch data from Spotify open, introducing by user (set bpm and beat start position) and calculate it by your beat detector. And in this third option when is calculated by web-audio-beat-detecotor i have to run analyze to get more accurate value and then once again guess to get  offset data. I think if more people you  just analyze function then you should left it not touched. 

Proposition:
Let function guess return not 2 values like now {bpm, offset) but three {bpm, offset, bpmFull}  or how you want call it. This third value will be not rounded raw bpm value. 

I just want avoid run analyze and guess to get not runded bpm and offset info. 


Thanks to share info about Essential.js function BeatTrackerMultiFeature seems to be promising but probably if will have to send this to speared microservice to don't push to much browser.


![djtruck](https://user-images.githubusercontent.com/33148232/104495400-0596d500-55d8-11eb-80e7-256e0117e08a.png)

**Comment by robert8888** [comment]
Sounds ok. It is short and clean name, pretty well describing what it is, so I think is good enough.

**Comment by chrisguttandin** [comment]
Thanks again to both of you for your input. The changes are published as v8.1.0.

**Comment by mindsocket** [comment]
Thanks Christoph! Sorry for not getting back to you before...

> That's an excellent tool. I would love to play around with it. Is that tool available on the internet?

Kind of, sort of, not really. It's an add-on that runs on top of Jira (issue tracker) to make Jira a DJ machine. Yes, really. :) Long story, but I've been hacking on it for years now and it's a bit of a snowflake that runs only on my setup at the moment. You're welcome to peek at the [extremely hacky code](https://glitch.com/edit/#!/rain-operation?path=app%2Faudio.js%3A1%3A0), but it will almost certainly make you wince, or you can [see it in action](https://youtu.be/KtMKy4KEUWU?t=1195), before I added the in-browser plotting and BPM measuring that I've been using behind the scenes.

**Comment by chrisguttandin** [comment]
That's a cool project. I wouldn't have thought that this library could end up running inside Jira. :-) Thanks for sharing.
