### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by joseluismurillorios** [chrisguttandin/web-audio-beat-detector#349]
I'm getting this bundle size after building my app:
![image](https://user-images.githubusercontent.com/11035303/151113584-a527f108-0efc-4af5-b423-a3e671084610.png)

I just wonder if this is normal, I looked over wabd repositories but couldn't find where this size comes from.

**Comment by chrisguttandin** [comment]
Hi @joseluismurillorios,

it's hard to tell what the problem is since the numbers in the graphic are relative.

web-audio-beat-detector is a pre-bundled version of two other packages called [web-audio-beat-detector-broker](https://github.com/chrisguttandin/web-audio-beat-detector-broker) and [web-audio-beat-detector-worker](https://github.com/chrisguttandin/web-audio-beat-detector-worker). As the names suggest the latter is meant to run in a Web Worker. To avoid any hiccups with misconfigured bundlers the worker code is converted to a string and included directly over here: https://github.com/chrisguttandin/web-audio-beat-detector/blob/master/src/worker/worker.ts.

If you want to reduce the bundle size of your initial bundle it would make sense to use web-audio-beat-detector-broker and web-audio-beat-detector-worker directly to load the Web Worker code lazily.

I hope this helps.

**Comment by joseluismurillorios** [comment]
Hi @chrisguttandin, it helped me a lot. I had to download some of the files to be able to use them properly with webpack 5, but now it generates an extra file that includes the processing of the worker, since the analysis is loaded lazy this drastically reduced the size of the main bundle.

Thank you very much for your help and for contributing such amazing work! I never imagined being able to get the bpm so quick and accurate in a web page, as I focus more on house music, I had to reduce the frequency to 180 hz to obtain better results.

```javascript
import { generateId } from '../../helper-util';
import { renderLowpass } from './beat-detector-render';

// TODO: add low frequency (options)

export const guessFromBuffer = async (audioBuffer, callback) => {
  const { channelData, sampleRate } = await renderLowpass(audioBuffer, 0, audioBuffer.duration);
  const worker = new Worker(new URL('./beat-detector-worker.js', import.meta.url));
  worker.onmessage = ({ data }) => {
    console.log('processWorker', data.result);
    callback(null, data.result);
  };
  const workerArgs = {
    id: generateId(),
    params: { channelData, sampleRate },
  };
  worker.postMessage(workerArgs);
};

export default guessFromBuffer;

```

**Comment by chrisguttandin** [comment]
That's good news. Do you happen to have the same graphic as posted above with the new numbers?

**Comment by joseluismurillorios** [comment]
The worker file only takes 3kb instead of 175kb

![image](https://user-images.githubusercontent.com/11035303/152960264-c1e2c079-f02f-4a5c-a1fb-458929cabc30.png)

**Comment by chrisguttandin** [comment]
I'm not sure if I understand that. I would have expected no worker file in the previous build with `web-audio-beat-detector` as its inlining the worker.

**Comment by joseluismurillorios** [comment]
Something happening with webpack probably, but I'm not sure

**Comment by chrisguttandin** [comment]
Interesting, I wasn't aware that webpack can extract inlined workers.
