### ISSUE TITLE
Feature Question

### ISSUE THREAD

**Issue by mhidro** [chrisguttandin/web-audio-beat-detector#39]
Is it possible to detect when the beat actually lands. For example to fire a callback when the beat lands or to return a list with the timing of the beats themselves? How hard would it be to do this with this codebase?

**Comment by chrisguttandin** [comment]
Hi @mhidro. Unfortunately it is not possible to fire a callback when an actual beat occurs (aka is played back) because this module does only analyze the given AudioBuffer but does not know when it is actually played back.

However the estimated position of each beat is known while computing the final BPM value. Therefore it might be possible to return the beat positions as well. But maybe returning a general offset which can then be used to calculate the position of each beat is a better solution.

Can you please provide some more details on your specific use case?

**Comment by mhidro** [comment]
I intend to make a simple visualization where a css class is added and then removed on each beat. Knowing the offset of the beat within the buffer would be ok. This is a mockup of what it might look like: 

https://jsfiddle.net/qbLw0qz6/

Click to see what I mean, when the beat comes the effect will be triggered.

**Comment by chrisguttandin** [comment]
Hi @mhidro , thanks for providing a bit more context. I think you might be better of by using a solution which builds on the [AnalyserNode](https://webaudio.github.io/web-audio-api/#the-analysernode-interface). If you Google for AnalyserNode and visualization you will for sure find a lot of examples.

However, I also extended the API of the `web-audio-beat-detector`. Version 4 does contain two methods now: `analyze()` and `guess()`. The first will return the tempo as it is analyzed by the algorithm and the second will round that tempo to BPM and return the potential offset of the first beat as well. Maybe that helps you.

But keep in mind that both functions treat the AudioBuffer as if it has as fixed tempo.

**Comment by mhidro** [comment]
Thanks this will be useful

**Comment by chrisguttandin** [comment]
I'm glad it helps you. I'm closing this issue now. Feel free to open a new one, when you run into problems again.
