### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by mfbx9da4** [chrisguttandin/web-audio-beat-detector#90]
Including 

```js
import { guess, analyze } from 'web-audio-beat-detector';
```

with webpack produces

```
./node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression

./node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
```

**Comment by chrisguttandin** [comment]
These should just be warnings. The [web-audio-beat-detector-broker](https://github.com/chrisguttandin/web-audio-beat-detector-broker) uses the [standardized-audio-context](https://github.com/chrisguttandin/standardized-audio-context) which uses the DI part of Angular. That's why the warnings show up in the logs.

Do you get errors instead of warnings?

**Comment by mfbx9da4** [comment]
Yes it's a warning but still quite annoying

![image](https://user-images.githubusercontent.com/1690659/31902335-fbd0e1a8-b7d0-11e7-98b4-ad31174b8683.png)

**Comment by chrisguttandin** [comment]
Yes, I agree it's annoying, but it's unfortunately outside this package's scope. Therefore I'm closing this issue.

**Comment by chrisguttandin** [comment]
Hi @mfbx9da4, it's been a while, but I'm happy that I'm finally able to tell you that Angular is no longer part of the dependency tree. The annoying warnings should be gone in version 6.0.25.
